// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  learnSidebar: [
    {type: 'autogenerated', dirName: 'learn'},
  ],
  buildSidebar: [
    {type: 'autogenerated', dirName: 'build'},
  ],
  nodeSidebar: [
    {type: 'autogenerated', dirName: 'nodes'},
  ],
  refSidebar: [
    {type: 'autogenerated', dirName: 'references'},
  ],
};

module.exports = sidebars;
